### ISSUE TITLE
上传到阿里云的图片文件类型不是image

### ISSUE THREAD

**Issue by kktt007** [PicGo/flutter-picgo#10]
## Bug Report

通过网页或picgo电脑端或者阿里云安卓端上传的image文件默认是image/jpeg类型。

但是通过此app最新版上传的jpg文件默认在阿里云oss里面是application/octet-stream,导致文件通过浏览器地址只能下载

### 您当前的flutter doctor信息或设备信息
andorid 6.1

### 预期的表现
打开网址后默认加载图片
### 实际的表现
打开网址后，不加载，直接下载到本地

**Comment by hackycy** [comment]
@kktt007 谢谢反馈，我复现下后确定问题后续版本修复

**Comment by hackycy** [comment]
@kktt007 已修复，请留意后续版本更新

**Comment by kktt007** [comment]
> @kktt007 已修复，请留意后续版本更新

收到,谢谢.
