### ISSUE TITLE
关于重命名

### ISSUE THREAD

**Issue by kktt007** [PicGo/flutter-picgo#11]
## Feature Request
现在上传的时候自动生成的是软件提供的名字，形如image_pickerxxxxxx，想知道能否用原始文件名，因为不需要改名字，但是上传默认已改名字了。
### 功能需求
就用文件本身的名字

**Comment by hackycy** [comment]
@kktt007 手机系统的限制暂无办法获取源文件的名称，应用内使用的ImagePicker插件就是这样的命名规则。你觉得过长可以设置默认时间戳命名。后续会想个折中的办法。

**Comment by kktt007** [comment]
> @kktt007 手机系统的限制暂无办法获取源文件的名称，应用内使用的ImagePicker插件就是这样的命名规则。你觉得过长可以设置默认时间戳命名。后续会想个折中的办法。

之前用的是阿里云端，是直接上传的文件，官方的吗，功能当然就只管上传，期待后期完善就完美了
