### ISSUE TITLE
能否支持多个文件选中功能

### ISSUE THREAD

**Issue by kktt007** [PicGo/flutter-picgo#12]
### 功能需求
能一次批量选中文件上传

**Comment by hackycy** [comment]
@kktt007 后续会提供支持，但进度会比较缓慢，最近比较忙。

**Comment by hackycy** [comment]
@kktt007 批量上传版本（1.9.2）已发布，Android / iOS均可支持下载。

**Comment by kktt007** [comment]
> @kktt007 批量上传版本（1.9.2）已发布，Android / iOS均可支持下载。

收到，这个功能太棒了，谢谢。
