### ISSUE TITLE
添加系统分享

### ISSUE THREAD

**Issue by kktt007** [PicGo/flutter-picgo#14]
### 功能需求
截图后想直接通过分享上传到picgo默认的图床。
另外能否透露下后期是否进入ipad商店，pencil截图后直接存储

**Comment by hackycy** [comment]
@kktt007 这个需要待考虑，需要编写插件配合的。优先级会比别的需求低哈。现版本没有考虑宽屏，后期解决界面的适配就可以支持ipad了。

**Comment by maoruibin** [comment]
免费版本的 picplus 就支持  https://www.yuque.com/gudong-osksb/twgz5k/bfdihv
