### ISSUE TITLE
能否添加配置备份功能

### ISSUE THREAD

**Issue by amrice** [PicGo/flutter-picgo#19]
## Feature Request

**仅限中文与英文**, 其他语言的提交将直接被关闭

### 功能需求
添加配置备份功能

### 描述您想要的功能.
希望能够云备份，比如webdav，或者接入对象存储，如果能直接导出到本地，也行

**Comment by hackycy** [comment]
@amrice 配置可以导出的呀，就在图床设置页面右下角的按钮。

![image](https://user-images.githubusercontent.com/26972260/103420241-4141a000-4bd1-11eb-9a96-ad750f68a8fd.png)

**点击后会把已有的配置信息导出到剪切板，你粘贴出来后去把文本转换成二维码就可以了。以后只要靠这个二维码用App扫码就能直接转换了。**
