### ISSUE TITLE
能否同步图片

### ISSUE THREAD

**Issue by Leader755** [PicGo/flutter-picgo#20]
## Feature Request

**仅限中文与英文**, 其他语言的提交将直接被关闭

### 功能需求
 图片同步功能

### 描述您想要的功能.
 是否能做到多个设备之间的数据同步，这个可能需要形成体系。那能否做到同步图床的图片呢，只要给足权限，这个同步图床图片应该部分图床是能够做到吧，全部可能很困难。picgo
 终将代替七牛云，又拍云自己的上传的软件。

**Comment by hackycy** [comment]
@Leader755 只要每个设备之间将图片上传到了图床，图床本身就存在数据了，同步的意义不大吧。而且应用内SM.MS、Github、Gitee、兰空、七牛云这些都可以进行管理（查看或者删除）内容。腾讯、又拍、阿里云管理功能得等后续有时间才会补上。
> 进入管理界面的方式在图床配置页面的右上角图标，如果没有则代表不支持

**Comment by Leader755** [comment]
我指的是，能拿到以前上传的照片。能将其全部同步到picgo进行展示。

**Comment by hackycy** [comment]
@Leader755 我了解你的意思，但该功能意义在哪？

**Comment by Leader755** [comment]
可能它已经不单单是一个图床工具了，成为了一个管理图片的工具。目前阶段确实不适宜，毕竟已经偏离了本质。等用户量大了，可以考虑下。

**Comment by hackycy** [comment]
@Leader755 后续版本迭代过程中再看看该功能的需求多不多再做考虑吧。谢谢建议哈。
