### ISSUE TITLE
一点建议

### ISSUE THREAD

**Issue by ZvonimirSun** [PicGo/flutter-picgo#21]
1. 希望能在相册里复制链接，现在没能找到哪里有图片链接
2. 图床仓库里的图片访问地址希望能够替换成自定义域名，比如说Github图床，自定义域名是用的jsdelivr的cdn链接
3. 上传进度的页面似乎退出了就找不到进入的地方了，以及上传失败的说明有点少，有时候是配置上的问题。毕竟手机上不像电脑上可以比较方便的看错误日志
4. 图床仓库入口隐藏的有点深，是不是能提到顶级目录比较好呢，然后加上隐藏其他图床的配置

**Comment by hackycy** [comment]
@ZvonimirSun 
1、相册里面**单击预览，双击复制链接，长按删除**哈。预览页面长按也可以进行相关操作。
2、自定义域名看下面的图片配置
![image](https://user-images.githubusercontent.com/26972260/104116202-7d070300-5351-11eb-9d3d-1239a1330b94.png)
3、上传进度页面没有保存的，退出就回不去了。
4、图床仓库入口的话，我是觉得不常用。而且也没过多优化。等有想法优化完了再提高它的显示优先级吧。
5、先等第四点完善好再考虑隐藏吧。因为现在的图床配置界面也不显眼。

**Comment by hackycy** [comment]
@ZvonimirSun 
第二点的补充，填写完上传后看预览界面有详细信息的哈
<img src="https://user-images.githubusercontent.com/26972260/104116419-53e77200-5353-11eb-800d-962ae629e1aa.png" width="400px" />

**Comment by ZvonimirSun** [comment]
好嘞，了解了，要是初次打开能有个简单说明就好了
