### ISSUE TITLE
一个很好的建议

### ISSUE THREAD

**Issue by ghost** [PicGo/flutter-picgo#22]
## Feature Request

**仅限中文与英文**, 其他语言的提交将直接被关闭

### 功能需求
加快GitHub图床在国内的访问速度

### 描述您想要的功能.
现在已经可以上传图片到github了，但是国内是加载不出来照片的，但是呢jsdeliver.com提供免费cdn，我觉得可以把picgo里面，生成的图片链接改一下，分为两个按钮，一个是github原来的链接，另一个是jsdeliver的链接，这样就会非常棒👍🏻！
jsdeliver使用方法
https://cdn.jsdelivr.net/gh/用户名/项目名/文件

**Comment by hackycy** [comment]
#21 看里面内容，使用自定义链接就可以配置成jsdeliver了

**Comment by ghost** [comment]
> #21 看里面内容，使用自定义链接就可以配置成jsdeliver了

啊太好了，谢谢你！

**Comment by ghost** [comment]
然后我又发现了一个新问题


上传失败后点击它就没反应了，能不能让他失败了以后，点一下重新上传

---原始邮件---
发件人: "YuanB"<notifications@github.com&gt;
发送时间: 2021年2月17日(周三) 晚上6:00
收件人: "PicGo/flutter-picgo"<flutter-picgo@noreply.github.com&gt;;
抄送: "fangaso"<Fangaso@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [PicGo/flutter-picgo] 一个很好的建议 (#22)




 
#21 看里面内容，使用自定义链接就可以配置成jsdeliver了

**Comment by hackycy** [comment]
@fangaso 失败的时候点一下红色的感叹号就可以重试重新上传了。

**Comment by ghost** [comment]
憨憨竟是我自己，😂



---原始邮件---
发件人: "YuanB"<notifications@github.com&gt;
发送时间: 2021年2月17日(周三) 晚上6:13
收件人: "PicGo/flutter-picgo"<flutter-picgo@noreply.github.com&gt;;
抄送: "fangaso"<Fangaso@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题: Re: [PicGo/flutter-picgo] 一个很好的建议 (#22)




 
@fangaso 失败的时候点一下红色的感叹号就可以重试重新上传了。

**Comment by hackycy** [comment]
还有问题再发问哈
