### ISSUE TITLE
可以支持自建的图床吗？比如win端安装web-uploader插件可以支持自建的chevereto图床

### ISSUE THREAD

**Issue by camelcdr** [PicGo/flutter-picgo#23]
## Feature Request

支持第三放图床

### 描述您想要的功能.
可以支持自建的图床吗？比如win端安装web-uploader插件可以支持自建的chevereto图床

**Comment by hackycy** [comment]
你可以先尝试用兰空图床，也是自建图床。现App已经支持兰空的。chevereto后续看看再考虑做支持。
