### ISSUE TITLE
1.9.2在google pxel 5 手机 安卓 11版本上，上传图片后无法预览

### ISSUE THREAD

**Issue by piqiuxiao** [PicGo/flutter-picgo#26]
## Bug Report

**仅限中文与英文**, 其他语言的提交将直接被关闭

### 您当前的flutter doctor信息或设备信息
1.9.2在google pxel 5 手机 安卓 11版本上，上传图片后无法预览

### 预期的表现
上传成功后，在相册中可以预览图片
### 实际的表现
上传成功后，在相册中无法预览图片
### 预期的分析 (给出您能想到, 任何您能想到的)
长按预览的图片将对应url地址放到浏览器中可以打开图片，在app中无法预览，可能这一块有问题。
### 重现的方式, 例如从 A界面 点击 b, 跳转到B页面, 界面出现溢出乱码等.
选择github图床，上传图片

**Comment by hackycy** [comment]
@piqiuxiao 给个图片预览示例地址

**Comment by piqiuxiao** [comment]
https://raw.githubusercontent.com/piqiuxiao/xpq/main/5952_origin_IMG_313093539_20210309_002636635.jpg

**Comment by hackycy** [comment]
@piqiuxiao 使用github地址基本上预览都是无法加载的，除非有vpn等方式加速github访问。
你可以参照 #21 来配置以达到预览的目的

**Comment by piqiuxiao** [comment]
> @piqiuxiao 使用github地址基本上预览都是无法加载的，除非有vpn等方式加速github访问。
> 你可以参照 #21 来配置以达到预览的目的

有科学上网，同一部手机，浏览器里能打开，手机设置有全局代理，app是否考虑了使用系统代理。

**Comment by hackycy** [comment]
@piqiuxiao 能上传但无法预览，应该是与图片预览插件相关了。如果选择设置代理所有流量也无法预览吗？

**Comment by piqiuxiao** [comment]
我设置的是全局代理，手机上其他app都能kx上网。

**Comment by hackycy** [comment]
@piqiuxiao 可能是图片预览插件相关，这个还要待验证，如果必须预览可以使用 #21 方法可以暂时解决这个问题哈。

**Comment by piqiuxiao** [comment]
ok
