### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by antbu** [PicGo/flutter-picgo#29]
看大佬是参考flutter-go做的，大佬有莫法本地运行flutter-go，虽然不维护了但感觉还是很有参考价值。

**Comment by hackycy** [comment]
@lyrbet 我就项目结构和一些代码作参考，我并没有直接运行过`flutter-go`噢，自己建立项目，参考下`flutter-go`项目结构就好了，具体一些库有变化再查一下变化的api吧，直接运行感觉没什么用，还不如参考些别的flutter项目

**Comment by antbu** [comment]
@hackycy 秒回啊，谢谢🙏 。我自己建项目来学习吧，谢谢大佬
