### ISSUE TITLE
Gitee图床中设定仓库所属空间地址指什么

### ISSUE THREAD

**Issue by Leee-Zzq** [PicGo/flutter-picgo#36]
其余设置扫描PC端picgo后自动填充，仅有第一项‘设定仓库所属空间地址’不知道填什么
填入仓库网址也会上传失败，点击gitee图床设置页面右上角的按钮会显示下图

![9168655ac88b440cb2196e5c461d742](https://user-images.githubusercontent.com/66564754/138587357-dd25cfd7-da75-462d-858a-839d2bedc8f5.jpg)

**Comment by hackycy** [comment]
@zzq15966331060 你的gitee用户名

**Comment by Leee-Zzq** [comment]
问题已解决：
插件gitee-uploader 1.1.2的图床设置只有一项”repo“，填入的是”用户名/仓库名“
通过扫描二维码导入flutter-picgo图床会将”repo“项填入仓库名，从而导致错误
应在“设定仓库所属空间地址”中填入gitee用户名
在“设定仓库名”中修改为仓库名。
