### ISSUE TITLE
请问何时可以上架iOS版或者有什么办法可以提前体验一下吗，谢谢！

### ISSUE THREAD

**Issue by declan-haojin** [PicGo/flutter-picgo#4]
如题，谢谢，如有打扰十分抱歉。

**Comment by hackycy** [comment]
@declan-haojin 

目前正在上架，但是因为相册权限描述不齐全导致被拒绝还在重新尝试，你可以发你的AppId绑定的邮箱发过来，下载TestFilght，我可以邀请你进行内测。

**Comment by declan-haojin** [comment]
declan@lihaojin.cn 谢谢

**Comment by hackycy** [comment]
@declan-haojin 
已经邀请了，但是目前通过TestFlight审核的只有1.0.3版，1.1.0支持SM.MS图床的还在等待审核中。

**Comment by declan-haojin** [comment]
谢谢！
