### ISSUE TITLE
安卓12闪退问题

### ISSUE THREAD

**Issue by Gasolcloudteam** [PicGo/flutter-picgo#44]
安卓12，MIUI13，小米11闪退

**Comment by feiquan666** [comment]
权限管理中把存储，相册访问等功能设置成始终允许就好了，不要设置尽在应用中允许

**Comment by Gasolcloudteam** [comment]
您好，感谢您的解答，虽然很久了，但我这段时间已经解决了。


---原始邮件---
发件人: &quot;bin ***@***.***&gt;
发送时间: 2022年9月25日(周日) 下午3:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PicGo/flutter-picgo] 安卓12闪退问题 (Issue #44)




 
权限管理中把存储，相册访问等功能设置成始终允许就好了，不要设置尽在应用中允许
 
&mdash;

**Comment by feiquan666** [comment]
你是咋解决？

**Comment by Gasolcloudteam** [comment]
如你所述


---原始邮件---
发件人: &quot;bin ***@***.***&gt;
发送时间: 2022年9月25日(周日) 下午4:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PicGo/flutter-picgo] 安卓12闪退问题 (Issue #44)




 
你是咋解决？
 
&mdash;

**Comment by zimistan** [comment]
解决了，谢谢
