### ISSUE TITLE
支持多种格式链接输出（URL，HTML，Markdown，UBB）,就像桌面端picgo一样

### ISSUE THREAD

**Issue by ghost** [PicGo/flutter-picgo#48]
## Feature Request

支持多种格式链接输出（URL，HTML，Markdown，UBB）,就像桌面端picgo一样

### 功能需求
需求如图，期待回复和加入计划
![图片](https://user-images.githubusercontent.com/112467275/196394795-e9e56358-6ce8-4af6-bbd9-7ea20eed0109.png)

**Comment by Kuingsmile** [comment]
可以试试我这个https://github.com/Kuingsmile/PicHoro 支持多个预设格式 还可以像PicGo一样自定义格式

**Comment by chancat87** [comment]
> [可以试试我这个https://github.com/Kuingsmile/PicHoro](https://github.com/Kuingsmile/PicHoro)支持多个默认格式还可以PicGo自定义格式

你这个我用了。。总是创建用户失败emm

**Comment by Kuingsmile** [comment]
我自己试了下是ok的呀。。密码需要是8位纯数字 会不会是这个问题

**Comment by chancat87** [comment]
。。。居然这么苛刻。。只能8位数😂

在 2022-10-30 21:55:00，"萌萌哒赫萝" ***@***.***> 写道：


我自己试了下是ok的呀。。密码需要是8位纯数字 会不会是这个问题

**Comment by Kuingsmile** [comment]
> 。。。居然这么苛刻。。只能8位数😂
> 
> 在 2022-10-30 21:55:00，"萌萌哒赫萝" ***@***.***> 写道：
> 
> 
> 我自己试了下是ok的呀。。密码需要是8位纯数字 会不会是这个问题
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***>

后面我会改改 确实有点苛刻了😂

**Comment by Georgebobby** [comment]
有這個功能嗎？
Horo 用不習慣而且github 私有倉庫的連結token好像有錯。一直404
