### ISSUE TITLE
一些建议，嘿嘿

### ISSUE THREAD

**Issue by Jim-Hepburn** [PicGo/flutter-picgo#5]
## Feature Request

**仅限中文与英文**, 其他语言的提交将直接被关闭

### 功能需求
>真是太好用了，非常喜欢!!

*  在上传的时候会自动复制，但是有时只是需要上传图片，希望上传后将链接输出在下方，自行复制.或者可以设置不自动复制
*  这么方便强大的软件希望不仅仅只能上传图片，写博文时也许要插入视频，希望加入上传视频、音乐的功能!
### 描述您想要的功能.
>1.  可设置上传时默认不自动复制，或者链接在下方输出.

>2.  可上传视频(mp4,rmvb,mkv,rm…)和音乐.

**Comment by hackycy** [comment]
@Jim-Hepburn 谢谢支持。
第一个功能会考虑加在后续版本上，不自动复制就可以了，需要再点击。
第二个的话想了想，这会和现在软件图床的定位有点冲突，而且有些第三方图床是不支持上传视频类型的。是否支持还是待考虑中。

**Comment by Jim-Hepburn** [comment]
好的!辛苦您了!
