### ISSUE TITLE
关于图床设置-图床管理的排序建议

### ISSUE THREAD

**Issue by biubox** [PicGo/flutter-picgo#8]
## Feature Request

**仅限中文与英文**, 其他语言的提交将直接被关闭

### 功能需求
图床管理的排序建议
### 描述您想要的功能.
刚刚使用发现sm.ms图床的内容管理排列貌似是上传的时间顺序，这样的话每次进去需要拉到最下面才能看之前的上传，希望开发者增加默认时间倒序，或者自定义排序。谢谢！

**Comment by hackycy** [comment]
@biubox 谢谢建议。SM.MS的[Upload_History](https://doc.sm.ms/#api-Image-Upload_History)APi没有支持排序。只能获取后本地再进行排序。那考虑增加个时间升序降序功能吧。
